# List of radio tiers and their respective radiuses
radiuses:
    # Format is tier: radius
    1: 1000
    2: 3000
    3: 10000
    
# List of radio tiers and their respective colors
colors:
    # Format is tier: COLOR_NAME
    1: YELLOW
    2: LIGHT_PURPLE
    3: RED